version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo No action required
  pre_build:
    commands:
      - echo No action required
  build:
    commands:
      - echo Build started on `date`
      - mvn install
    post_build:
      commands:
        - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - 'target/helloworld.war'
    - 'appspec.yml'
    - 'scripts/before_install.sh'
    - 'scripts/after_install.sh'
    - 'scripts/start_server.sh'
    - 'scripts/stop_server.sh'